source "http://rubygems.corp.intuit.net"

# Declare your gem's dependencies in intuit_com_cms.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails"
gem "showroom_plugin", '~> 1.0.15'
gem "showroom_cms", '~> 1.12.20'
#gem "showroom_cms", :path => "../../showroom_cms/dev"
gem 'therubyracer', '~> 0.11.4'
gem 'nokogiri'

gem 'sass-rails', '~> 3.2.3'
gem 'uglifier', '>= 1.0.3'

group :development, :test do
  gem 'rspec-rails', '>= 2.7.0'
  gem 'capybara'
  gem 'factory_girl_rails', '>= 1.3.0'
  gem "maksar-remarkable_activerecord", "~> 4.0.0.alpha6" ##using maksar fork to remove deprication warnings. see https://github.com/carlosbrando/remarkable/pull/21
  gem 'ruby-prof' ##fast code profiler

  gem 'rcov', '~>0.9.11'
  gem 'simplecov', :require => false, :group => :test
end
